package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "table-product")
public class ProductEntity {

    /*
    Workaround - Spring data @Id is mandatory in Entity Map
     */
    @Id
    private ProductEntityId productEntityId;
    private Float value;
    private Integer createDate;

    @DynamoDBAttribute(attributeName = "value")
    public Float getValue () {
        return value;
    }

    public void setValue (final Float value) {
        this.value = value;
    }

    @DynamoDBIndexRangeKey(attributeName = "create-date", globalSecondaryIndexName = "productDateIndex")
    public Integer getCreateDate () {
        return createDate;
    }

    public void setCreateDate (final Integer createDate) {
        this.createDate = createDate;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBIndexHashKey(attributeName = "id", globalSecondaryIndexName = "productDateIndex")
    public String getId () {
        return productEntityId != null ? productEntityId.getId() : null;
    }

    public void setId (final String id) {
        if (productEntityId == null) {
            productEntityId = new ProductEntityId();
        }
        productEntityId.setId(id);
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName () {
        return productEntityId != null ? productEntityId.getName() : null;
    }

    public void setName (final String name) {
        if (productEntityId == null) {
            productEntityId = new ProductEntityId();
        }
        productEntityId.setName(name);
    }

    @Override
    public String toString () {
        final StringBuilder builder = new StringBuilder()//
                .append("ProductEntity [")//
                .append("productEntityId=")//
                .append(productEntityId)//
                .append(",value=")//
                .append(value)//
                .append(",createDate=")//
                .append(createDate)//
                .append("]");
        return builder.toString();
    }
}